# Generated by Django 4.1.2 on 2022-10-23 22:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_listing_finalbid_alter_listing_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bidPrice',
            field=models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Bid Amount'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='currentBid',
            field=models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Starting Bid'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='dateBidEnd',
            field=models.DateField(default=datetime.date.today, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='datePosted',
            field=models.DateField(default=datetime.date.today, verbose_name='Date Posted'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='finalBid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, verbose_name='Sold for'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(blank=True, default='auctions/images/noimage.jpeg', upload_to='auctions/images', verbose_name='Images'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to=settings.AUTH_USER_MODEL, verbose_name='Sold to'),
        ),
    ]
