# Generated by Django 4.1.2 on 2022-10-24 22:28

import auctions.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_listing_datebidend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='dateBidEnd',
            field=models.DateField(default=datetime.date(2022, 10, 31), validators=[auctions.models.validate_bidEndDate], verbose_name='End Date'),
        ),
    ]
