# Generated by Django 4.1.2 on 2022-10-23 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_bid_bidprice_alter_listing_currentbid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default='auctions/images/noimage.jpeg', upload_to='auctions/images', verbose_name='Images'),
        ),
    ]
