# Generated by Django 4.1.2 on 2022-10-18 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_category_listing_user_listing_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='description',
            field=models.TextField(default='', max_length=200),
        ),
    ]
