# Generated by Django 4.1.2 on 2022-10-23 21:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_listing_datebidend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='datePosted',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
