# Generated by Django 4.1.2 on 2022-10-18 20:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_listing_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='datePosted',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
