# Generated by Django 4.1.2 on 2022-10-23 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_listing_finalbid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='finalBid',
        ),
    ]
