# Generated by Django 4.1.2 on 2022-10-23 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_remove_listing_finalbid'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='finalBid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=19),
        ),
    ]
