# Generated by Django 4.1.2 on 2022-10-18 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_alter_listing_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='image',
            field=models.ImageField(blank=True, default='images', null=True, upload_to=''),
        ),
    ]
