# Generated by Django 4.1.2 on 2022-10-18 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_listing_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(default='images', upload_to='djangouploads/files/covers'),
        ),
    ]
