# Generated by Django 4.1.2 on 2022-10-23 21:56

import auctions.validators
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_alter_listing_category_alter_listing_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='dateBidEnd',
            field=models.DateField(default=datetime.date.today, validators=[auctions.validators.validate_date]),
        ),
    ]
