# Generated by Django 4.1.2 on 2022-10-19 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_alter_bid_listing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='startingBid',
            new_name='currentBid',
        ),
    ]
