# Generated by Django 4.1.2 on 2022-10-21 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_alter_listing_category_alter_listing_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(default='auction/images/noimage.jpeg', upload_to='auction/images'),
        ),
    ]
