# Generated by Django 4.1.2 on 2022-10-21 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_alter_listing_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(default='auctions/images/noimage.jpeg', upload_to='auctions/images'),
        ),
    ]
